# Generated by Django 6.0.7 on 2026-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('company_brand', models.CharField(max_length=120, verbose_name='公司/品牌')),
                ('project_type', models.CharField(max_length=80, verbose_name='项目类型')),
                ('estimated_quantity', models.CharField(max_length=80, verbose_name='预计数量')),
                ('delivery_city', models.CharField(max_length=80, verbose_name='交付城市')),
                ('budget_range', models.CharField(max_length=80, verbose_name='预算区间')),
                ('requirement_description', models.TextField(verbose_name='需求说明')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'db_table': '合同',
            },
        ),
    ]
