# Generated by Django 6.0.7 on 2026-07-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '联系表单', 'verbose_name_plural': '联系表单'},
        ),
    ]
